* Quirky computing books

** <2022-07-29 Fri>
/Designing & Programming Personal Expert Systems/ by Townsend Feucht

About the quirkiest computing book that you can imagine. It describes the implementation of expert systems in Forth by building a Lisp-like substrate which is then used to build a Prolog that is eventually used to implement the production rules system. It's a near perfect book for me. 

That said, the discussion has many lacunae, making the actual realization of the described system exceedingly difficult.

- TWEET: https://twitter.com/fogus/status/1553013447205560320
- READ:  https://archive.org/details/designingprogram0000town
- BUY:   [[https://www.amazon.com/Designing-Programming-Personal-Expert-Systems/dp/0830606920/?tag=fogus-20][currently NOT difficult to find]]


** <2022-07-06 Wed>
/Algorithms for RPN Calculators/ by John Ball

The inimitable @mfikes sent a copy of this astonishing book last week and I've been gobsmacked by it ever since. This books presents a boatload of mathematical functions described as series of keystrokes. As a minor calculator dweeb there is much to learn here!

- TWEET: https://twitter.com/fogus/status/1544765860711206915
- READ:  https://archive.org/details/algorithmsforrpn0000ball
- BUY:   [[https://www.amazon.com/Algorithms-RPN-Calculators-John-Ball/dp/B000PS56JW/?tag=fogus-20][currently difficult to find]]

** <2022-06-27 Mon>
/Electronic Calculators/ by H. Edward Roberts, then president of MITS, Inc.

In 1974, electronic calculators were the maker culture focal point even after the release of the MITS Altar 8800. For many electronics hobbyists, the calculator was financially and conceptually in reach. This book may have been an invaluable resource for folks trying to build their own.

For calculator enthusiasts this book has a lot to offer. From history, to industry standards of the time, to I/O considerations, there's a lot to take in. It's hard to say if one could start from zero and end up with a functioning device -- my gut says no.

- TWEET: https://twitter.com/fogus/status/1541480499281121284
- READ: n/a
- BUY: [[https://www.amazon.com/Electronic-Calculators-H-Edward-Roberts/dp/0672210398/?tag=fogus-20][currently difficult to find]]

** <2022-06-22 Wed>
/Functional Programming: Application and Implementation/ by Peter Henderson

Inspired by a question on my last book tweet, I thought I'd show another FP offering. This is an original work by Henderson that focuses the discussion around a language called LispKit Lisp, an impl targetting an SECD machine.

The book delves into the implementation of LispKit Lisp and provides a mountain of fine details and source code to facilitate other implementations. It's a good book but one that's on the bubble in my personal library. https://en.wikipedia.org/wiki/Lispkit_Lisp

One fine note is that I love when these old books had ads for other books in the same thematic line. Prentice Hall at the time was great at this and led me to many a book that I wouldn't have found otherwise.

- TWEET: https://twitter.com/fogus/status/1539663473516244992
- READ: https://archive.org/details/functionalprogra0000hend
- BUY: [[https://www.amazon.com/Functional-Programming-Application-Implementation-Henderson/dp/0133315797/?tag=fogus-20][currently readily available]]

** <2022-06-21 Tue>
/Functional Programming and Its Applications/ by Darlington, Henderson, and Turner

This particular book is on the bubble for my collection as much of what it contains is found scattered throughout other books in my library.

Of particular interest is Henderson's paper "Purely Functional Operating Systems" which was difficult to find the last I checked.

- TWEET: https://twitter.com/fogus/status/1539325385946562560
- READ8: n/a
- BUY: [[https://www.amazon.com/gp/product/0521245036/?tag=fogus-20][somewhat scarce these days]]
